name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x buildscripts/update_version.sh

      - name: Update version
        run: ./buildscripts/update_version.sh

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "manifest.json"
          message: "Update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
